# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/PhD/Vivado_projects/parallella-hw/fpga/projects/HARMONIA_analog_monitoring/my_ips/stabilization_prop_mon_generic.cache/wt [current_project]
set_property parent.project_path C:/PhD/Vivado_projects/parallella-hw/fpga/projects/HARMONIA_analog_monitoring/my_ips/stabilization_prop_mon_generic.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths C:/PhD/Vivado_projects/parallella-hw/fpga/projects/HARMONIA_analog_monitoring/my_ips [current_project]
read_verilog -library xil_defaultlib {
  {C:/HARMONIA repo/code/SPI example/my_IP_core/my_IP_core.srcs/sources_1/new/shift_reg_buffer.v}
  C:/PhD/Vivado_projects/parallella-hw/fpga/projects/HARMONIA_analog_monitoring/my_ips/stabilization_prop_mon/stabilization_property_mon.v
}
catch { write_hwdef -file stabilization_property_mon.hwdef }
synth_design -top stabilization_property_mon -part xc7z020clg484-1
write_checkpoint -noxdef stabilization_property_mon.dcp
catch { report_utilization -file stabilization_property_mon_utilization_synth.rpt -pb stabilization_property_mon_utilization_synth.pb }
